Create hero section
m3ntorship/m3ntorship.com-v2 pull request #19
Opened 2022-07-05 14:04 UTC by MAlngaawy

Task #8 

Create the homepage hero section

2022-07-05 23:03 UTC, elhaw commented on tailwind.config.js
> +      default: "#fafafa",
I think the class for that color is already generated `bg-background`

2022-07-05 23:03 UTC, elhaw commented on src/modules/HomePage/components/HeroSection/Navbar.tsx
> +};
It is good job to create a reusable NavItem component but let us organize the code in a separate folder

2022-07-11 16:18 UTC, atwfk requested changes
we will align with @elhaw to restructure the project folders and I will update you here or in the meeting if possible,
Great efforts :muscle::muscle:

2022-07-11 16:18 UTC, atwfk commented on src/modules/HomePage/components/HeroSection/Navbar.tsx
> +        className={classNames(
Use the `clsxm` utility function exported from lib folder,
it uses [clsx](https://www.npmjs.com/package/clsx) which is faster and smaller than [classnames](https://www.npmjs.com/package/classnames)

2022-07-11 16:18 UTC, atwfk commented on src/modules/HomePage/components/HeroSection/Navbar.tsx
> +      <Link href={href}>
Use the `Link` component exported from `m3ntorship-ui`

2022-07-11 16:18 UTC, atwfk commented on src/modules/HomePage/components/HeroSection/Navbar.tsx
> +  return (
It's better to move the classes you used here in the jsx return to css file to be more readable

2022-07-11 16:18 UTC, atwfk commented on src/modules/HomePage/components/HeroSection/index.tsx
> +  return (
It's better to move the classes you used here in the jsx return to css file to be more readable

2022-07-11 16:18 UTC, atwfk commented on src/modules/HomePage/components/HeroSection/sizeHook.tsx
> +function useWindowSize(): Size {
I think it's better to return a flag from this hook, which will be true or false based on the max and min width we will pass as an argument to this hook, something like:
```typescript
const matched = useMedia('(max-width: 900px)'); 
```
take a look at [matchMedia api](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia)

2022-07-11 16:18 UTC, atwfk commented on src/modules/HomePage/components/HeroSection/index.tsx
> +        <span className='absolute right-0 z-0 h-full w-5/12 rounded-br-lrg rounded-bl-lrg bg-white shadow-shd-1'></span>
the two boxes positioned behind Hero section here don't match Figma UI, ensure the dimensions are the same as in Figma

2022-07-16 11:15 UTC, atwfk approved these changes
LGTM

2022-07-16 11:25 UTC, merged