Feature/how it wroks section
m3ntorship/m3ntorship.com-v2 pull request #25
Opened 2022-07-06 12:49 UTC by elhaw

#10 
Description : 

- [x]  Created reusable component for process card ( HTML, styles, ts types)
- [x]  Crated component for the whole section 
- [x] Responsiveness

2022-07-06 13:10 UTC, atwfk requested changes
the section styling has some issues when I'm on less than 600px screen, please check them

2022-07-06 13:10 UTC, atwfk commented on src/modules/HomePage/components/JoiningProcessFlow/JoiningProcessFlow.module.css
> +@media screen and (max-width: 375px) {
Please add this media width as constant to reuse it again or add it to tailwind.config file

2022-07-06 13:10 UTC, atwfk commented on src/modules/HomePage/components/JoiningProcessFlow/ProcessCard/ProcessCard.module.css
> +  max-width: 17ch;
add this value in tailwind.config and access it through `@apply` directive,
it's better to use only one approach when styling our pages

2022-07-06 13:10 UTC, atwfk commented on src/modules/HomePage/components/JoiningProcessFlow/ProcessCard/ProcessCard.module.css
> +    max-width: unset;
same as the above comment

2022-07-06 13:10 UTC, atwfk commented on src/modules/HomePage/components/JoiningProcessFlow/ProcessCard/index.tsx
> +    <div className='flex border-spacing-xs items-center bg-background-surface p-lrg shadow-shd-1'>
I see a lot of tailwind classes here, it would be better to separate these classes form this file and add them in css file

2022-07-06 13:10 UTC, atwfk commented on src/modules/HomePage/components/JoiningProcessFlow/index.tsx
> +        <div className='grid gap-med  py-xxxxl small:grid-cols-1 small:gap-x-med large:grid-cols-3 large:gap-xl'>
same as the comment in [this file](https://github.com/m3ntorship/m3ntorship.com-v2/blob/eaee925369ebc56f870dc1937aedb0fe9a6f6a48/src/modules/HomePage/components/JoiningProcessFlow/ProcessCard/index.tsx)

2022-07-06 13:10 UTC, atwfk commented on src/modules/HomePage/components/JoiningProcessFlow/ProcessCard/ProcessCard.module.css
> +@media screen and (min-width: 375px) and (max-width: 1024px) {
same as the comment in [this file](https://github.com/m3ntorship/m3ntorship.com-v2/blob/eaee925369ebc56f870dc1937aedb0fe9a6f6a48/src/modules/HomePage/components/JoiningProcessFlow/JoiningProcessFlow.module.css)

2022-07-11 20:01 UTC, elhaw commented on src/modules/HomePage/components/JoiningProcessFlow/ProcessCard/ProcessCard.module.css
> +  max-width: 17ch;
ok, will add it

2022-07-11 21:50 UTC, elhaw commented on src/modules/HomePage/components/JoiningProcessFlow/ProcessCard/ProcessCard.module.css
> +@media screen and (min-width: 375px) and (max-width: 1024px) {
I have used the theme() function to reference the screen sizes in tailwindconfig.js

2022-07-12 09:09 UTC, atwfk approved these changes
LGTM

2022-07-12 10:51 UTC, merged