Create alumni section
m3ntorship/m3ntorship.com-v2 pull request #35
Opened 2022-07-16 13:56 UTC by MAlngaawy

#12 
Create Alumni section

2022-07-19 11:45 UTC, atwfk requested changes

2022-07-19 11:45 UTC, atwfk commented on src/modules/HomePage/components/organisms/AlumniSection/index.tsx
> +            <Button
this should be Link component. it will navigate the user to `alumni` page

2022-07-19 11:45 UTC, atwfk commented on src/modules/HomePage/components/organisms/AlumniSection/index.tsx
> +          />
add these data to an array and map over them, this will render data coming from an API response in the future

2022-07-19 11:45 UTC, atwfk commented on src/modules/HomePage/components/molecules/AlumniCard/index.tsx
> +        }}
why can't we use **NextImage** component to display this image?

2022-07-19 19:30 UTC, MAlngaawy commented on src/modules/HomePage/components/molecules/AlumniCard/index.tsx
> +        }}
because it's a background image, not an IMG element

2022-07-19 19:34 UTC, atwfk commented on src/modules/HomePage/components/molecules/AlumniCard/index.tsx
> +        }}
You can position it and give the others z-index to be displayed in the card's background, 
There's other solutions of course but using the native html img element is not recommended

2022-07-19 19:40 UTC, MAlngaawy commented on src/modules/HomePage/components/molecules/AlumniCard/index.tsx
> +        }}
Ok, I’ll try this solution

2022-07-20 11:29 UTC, atwfk approved these changes
LGTM

2022-07-20 12:32 UTC, merged